sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t hackman2007/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true hackman2007/docker-react npm run test

