sudo: required
language: generic

services:
          - docker

before_install:
          - docker build -t hackman2007/docker-react -f Dockerfile.dev .

script:
          - docker run -e CI=true hackman2007/docker-react npm run test

deploy:
          provider: elasticbeanstalk
            region: 'us-east-2'
              app: 'docker'
                env: 'docker-env'
                  bucket_name: 'elasticbeanstalk-us-east-2-361794881103'
                    bucket_path: 'docker'
                      on:
                                  branch: main
                      access_key_id: $AWS_ACCESS_KEY
                      secret_access_key:
                              secure:"$AWS_SECRET_KEY"
